/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sprpr
 */
public class teacherres2 extends javax.swing.JFrame {

    /**
     * Creates new form teacherres2
     */
    String x,y,z;
    String a,b,c;
    String n;
    String w;
    public teacherres2() {
        initComponents();
    }
      public teacherres2(String d,String e,String f) {
        initComponents();
        x=d;
        y=e;
        z=f;
        jTextField1.setText(d);
        jTextField2.setText(e);
        jTextField3.setText(f);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sprpr\\Downloads\\th (1).jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("STUDENT DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(11, 68, 202, 25);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 111, 219, 26);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(0, 173, 219, 26);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(116, 22, 103, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("TEACHER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 28, 110, 27);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 233, 135, 33);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Question_ID", "Question", "Answer"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(231, 11, 710, 260);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(10, 350, 213, 38);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("MARK SECURED");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 300, 213, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(240, 280, 540, 260);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 560, 210, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 560, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TOTAL MARK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 400, 190, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(10, 440, 220, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mark"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(940, 10, 100, 260);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(700, 560, 190, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sprpr\\Downloads\\th (1).jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-3, 6, 1040, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try{
           Class.forName("com.mysql.jdbc.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/studentloginpage","root","");
java.sql.Statement st=con.createStatement();
java.sql.ResultSet rs=st.executeQuery("select * from studentanswerpanel where id_number='"+z+"'and stud_regno='"+y+"'");
System.out.println("Success");
//jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//String columns[] = { "Question ID", "Question", "Option1","Option2","Option3","Option4","Answer" };
//String data[][] = new String[10][7];
//DefaultTableModel model=new DefaultTableModel();
//model.setColumnIdentifiers(columns);
//JTable table = new JTable();
//String a=jTextField1.getText();

    
      int i = 0;
      while (rs.next()) {
        String qnid= rs.getString("qn_id");
        String ques = rs.getString("qn");
        String ans = rs.getString("answer");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      model.addRow(new Object[]{qnid,ques,ans});
        i++;
      }
    
      //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      //model.addRow(data);
      


        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,e1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //String re;
        int j=jTable1.getSelectedRow();
        TableModel model1=jTable1.getModel();
        String d=model1.getValueAt(j,2).toString();
        w=model1.getValueAt(j,1).toString();
        
        
        
        //t=model1.getValueAt(j,3).toString();
        
        /*int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        //jTextField2.setText(model.getValueAt(i,1).toString());
         //jTextField3.setText((String) model.getValueAt(i,0));
         a=model.getValueAt(i,0).toString();
         b=model.getValueAt(i,1).toString();
         c=model.getValueAt(i,2).toString();
         //teacherres2 t1=new teacherres2();
         //re=t1.x;
         teacherres3 t=new teacherres3(a,b,c,y);
         t.show();*/
        jTextArea2.setText(d);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        n=jTextField4.getText();
        teacherres t=new teacherres(x,y,z,n);
        t.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        try{
            Class.forName("com.mysql.jdbc.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/studentloginpage","root","");
java.sql.Statement s = con.createStatement();
String s1="insert into teacheransevaluation(qn_id,qn,answer,mark,stud_regno) values('"+jTextField3.getText()+"','"+w+"','"+jTextArea2.getText()+"','"+jTextField4.getText()+"','"+jTextField2.getText()+"');";
//String s1 = "insert into student_registration_2(regno,set_username,set_password,clue,answer) values('"+jTextField2.getText()+"','"+jTextField1.getText()+"','"+jPasswordField1.getText()+"','"+a+"','"+jTextField5.getText()+"');";
System.out.println("sucess");
s.executeUpdate(s1);
System.out.println("Success");

        }
        catch(ClassNotFoundException | SQLException h1)
        {
            System.out.println(h1);
        }
DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
      model.addRow(new Object[]{jTextField4.getText()});
    
    
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String a=jTextField2.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/studentloginpage","root","");
java.sql.Statement s = con.createStatement();
String s1="insert into teachertotalmark(name,regno,id_number,totalmark) values('"+jTextField1.getText()+"','"+a+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"');";
//String s1 = "insert into student_registration_2(regno,set_username,set_password,clue,answer) values('"+jTextField2.getText()+"','"+jTextField1.getText()+"','"+jPasswordField1.getText()+"','"+a+"','"+jTextField5.getText()+"');";
System.out.println("sucess");
s.executeUpdate(s1);
System.out.println("Success");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherres2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherres2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherres2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherres2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherres2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
